name = "mat_tests"
description = "Memory Analysis Tool"
version = "1.2.0"

authors = ["Stephane.Carrez@gmail.com"]
maintainers = ["Stephane.Carrez@gmail.com"]
maintainers-logins = ["stcarrez"]
licenses = "Apache-2.0"
website = "https://github.com/stcarrez/mat"
tags = ["memory", "profiler", "analysis"]

project-files = ["mat_tests"]

[[depends-on]]
utilada = "^2.8.0"
utilada_xml = "^2.8.0"
utilada_unit = "^2.8.0"
mat = "*"

[[pins]]
mat = { path = ".." }

[configuration]
disabled = true
